ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios

# Lab-only: allow legacy SSH algorithms for old IOS images
ansible_host_key_checking: false
ansible_ssh_common_args: >-
  -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
  -o HostKeyAlgorithms=+ssh-rsa
  -o PubkeyAcceptedAlgorithms=+ssh-rsa
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null

